security:
    encoders:
         App\Entity\User:
            algorithm: bcrypt
   
    providers:
        database_users:
            entity:
                 class: App\Entity\User 
                 property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|build|images|js)/
            security: false

        main:
          
            anonymous: true

             
                
    

       

     #  access_control:
          #  - { path: '^/login', roles: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: '^/user', roles: [IS_AUTHENTICATED_FULLY, IS_AUTHENTICATED_REMEMBERED] }

